version: '3'

services:
  am-api:
    container_name: am-api
    env_file: './strife-server/account-management-api/.env'
    build:
      context: './strife-server/account-management-api'
      dockerfile: './Dockerfile'
    ports:
      - '3001:3001'

  ua-api:
    container_name: ua-api
    env_file: './strife-server/user-authorization-api/.env'
    build:
      context: './strife-server/user-authorization-api'
      dockerfile: './Dockerfile'
    ports:
      - '3002:3002'

  sc-api:
    container_name: sc-api
    env_file: './strife-server/strife-chat-api/.env'
    build:
      context: './strife-server/strife-chat-api'
      dockerfile: './Dockerfile'
    ports:
      - '5000:5000'
