FROM alpine:latest
RUN apk add --no-cache bash
RUN rm -f /etc/nginx/conf.d/strife.chat.staging.conf
COPY strife.chat.conf /etc/nginx/conf.d/strife.chat.staging.conf
ENTRYPOINT ["echo", "Copied staging NGINX config"]